---
params:
  token: 'default'
status: 200
payload: '
  {
    "scope": ["openid", "identite_pivot"],
    "client": {
      "client_id": "client_id",
      "client_name": "client_name"
    },
    "identity": {
      "given_name": "Jean Martin",
      "family_name": "DUPONT",
      "birthdate": "2000-01-01",
      "gender": "male",
      "birthplace": "75101",
      "birthcountry": "99100",
      "preferred_username": "jdupont"
    }
  }
'
