---
params:
  nom: 'Moustaki'
  prenoms: 'Georges Claude'
  dateDeNaissance: '1992-11-29'
  lieuDeNaissance: 'Poitiers'
  sexe: 'M'
status: 200
payload: |-
  {
    "nom": "Moustaki",
    "prenom": "Georges",
    "prenom2": "Claude",
    "dateNaissance": "1992-11-29",
    "lieuNaissance": "Poitiers",
    "sexe": "M",
    "boursier": true,
    "echelonBourse": "6",
    "email": "georges@moustaki.fr",
    "dateDeRentree": "2019-09-01",
    "dureeVersement": 12,
    "statut": 0,
    "statutLibelle": "définitif",
    "villeEtudes": "Brest",
    "etablissement": "Carnot"
  }
