name: Reload backend periodicaly
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  reload_backend:
    name: Reload backend periodicaly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Reload mock backend on staging
        run: |
          bundle exec ruby bin/reload_mock_backend.rb
