name: Tests
on:
  push:
  pull_request:
    types:
      - opened
jobs:
  test:
    name: Tests (RSpec)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec

      - name: Force push develop to main
        run: |
          if [ "$(git branch --show-current)" = "develop" ] ; then
            git reset --hard && \
              git push --force origin develop:main && \
              git fetch && \
              [[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow

            exit 0
          fi

      - name: Reload mock backend on staging
        run: |
          if [ "$(git branch --show-current)" = "develop" ] ; then
            bundle exec ruby bin/reload_mock_backend.rb
          fi
